In [ ]:
import numpy as np

def activation(sstm):
    solution=[]
    for i in sstm:
        soln=[]
        for j in i:
            if j>0:
                soln.append(1)
            else:
                soln.append(-1)
        solution.append(soln)
    return np.array(solution)

def autoassoc(inputMatrix, testMatrix, trainCheckList):
    im=np.array(inputMatrix)
    tm=np.array(testMatrix)
    
    im=im.transpose()
    stm=im@tm
    print("weight matrix=sTranspose*train matrix")
    print(stm)
    
    print("test matrix*weight matrix")
    sstm=trainCheckList@stm
    print(sstm)
    
    print("result")
    ssstm=activation(sstm)
    print(ssstm)
    
    print("overall result")
    for i in range(len(ssstm)):
        print(ssstm[i]==tm)
    
    
print(autoassoc([[-1,1,1,1]],[[-1,1,1,1]],[[-1,0,1,1],[1,1,1,1],[0,0,1,1],[1,-1,1,1]]))
    

weight matrix=sTranspose*train matrix
[[ 1 -1 -1 -1]
 [-1  1  1  1]
 [-1  1  1  1]
 [-1  1  1  1]]
test matrix*weight matrix
[[-3  3  3  3]
 [-2  2  2  2]
 [-2  2  2  2]
 [ 0  0  0  0]]
result
[[-1  1  1  1]
 [-1  1  1  1]
 [-1  1  1  1]
 [-1 -1 -1 -1]]
overall result
[[ True  True  True  True]]
[[ True  True  True  True]]
[[ True  True  True  True]]
[[ True False False False]]
None
